import './global.css';
import { commieFont } from 'apps/web/public/fonts/communist/commie.font';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={commieFont.className}>{children}</body>
    </html>
  );
}
